version: "3"
services:
  app:
    image: ruby:2.6.6
    volumes:
      - ./:/app
    working_dir: /app
    tty: true
    command: bundle exec rdebug-ide --host 0.0.0.0 --port 1234 --dispatcher-port 26162 -- bin/rails s -b 0.0.0.0
    environment:
      - BUNDLE_APP_CONFIG=/app/.bundle
    user: "${UID}:${GID}"
    ports:
      - 3100:3000
      - 1234:1234
      - 26162:26162
