version: "3"
services:
  app:
    build: .
    working_dir: /app
    tty: true
    command: bundle exec rails s -b 0.0.0.0
    environment:
      - BUNDLE_APP_CONFIG=/app/.bundle
    # user: "${UID}:${GID}"
    ports:
      - 3100:3000
