version: "3"
services:
  app:
    image: ruby:2.6.6
    volumes:
      - app-bundle:/app/vendor/bundle
      - app-node_module:/app/node_module
      - ./:/app
    working_dir: /app
    tty: true
    environment:
      - BUNDLE_APP_CONFIG=/app/.bundle
    user: "${UID}:${GID}"
    ports:
      - 3100:3000
  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '12280:80'
      - '12443:443'
    restart: always
    environment:
      DOMAINS: 'test.starferry.net -> http://app:3100'
      # STAGE: 'production' # Don't use production until staging works
      # FORCE_RENEW: 'true'

volumes:
  app-bundle:
  app-node_module:
  db-data:
